model_config:
  network_config:
    spatial_dims: 3
    in_channels: 1
    out_channels: 1
    channels: [64, 128, 256, 320, 320]
    strides: [2, 2, 2, 2]

  opt_args: 
    lr: 0.005
    weight_decay: 0.0
    # beta?

data_config:
  batch_size: 10    # 10 for Alex, 2 for my machint

trainer:
  accelerator: 'gpu'
  precision: 16
  max_epochs: 200
  check_val_every_n_epoch: 1

pretrained: ''