model_config:
  network_config:
    spatial_dims: 3
    in_channels: 1
    out_channels: 1
    channels: [16, 32, 64, 64, 64]
    strides: [2, 2, 2, 2]

  opt_args: 
    lr: 0.0005
    weight_decay: 0.01
    # beta?

data_config:
  batch_size: 30    # 30 for Alex, 2 for my machint

trainer:
  accelerator: 'gpu'
  precision: 16
  max_epochs: 200
  check_val_every_n_epoch: 4

